export const casinoGameCardTokens = {
  bg: '--zg-casino-game-card-bg',
  borderColor: '--zg-casino-game-card-border-color',
  radius: '--zg-casino-game-card-radius',
  shadow: '--zg-casino-game-card-shadow',
  overlayBg: '--zg-casino-game-card-overlay-bg',
  placeholderBg: '--zg-casino-game-card-placeholder-bg',
  titleColor: '--zg-casino-game-card-title-color',
  providerColor: '--zg-casino-game-card-provider-color',
  iconButtonBg: '--zg-casino-game-card-icon-button-bg',
  iconColor: '--zg-casino-game-card-icon-color',
  favoriteColor: '--zg-casino-game-card-favorite-color',
  favoriteActiveColor: '--zg-casino-game-card-favorite-active-color',
  playButtonBg: '--zg-casino-game-card-play-button-bg',
  playButtonColor: '--zg-casino-game-card-play-button-color',
  aspectRatioPortrait: '--zg-casino-game-card-aspect-ratio-portrait',
  aspectRatioSquare: '--zg-casino-game-card-aspect-ratio-square',
  topRowOffset: '--zg-casino-game-card-top-row-offset',
  topRowGap: '--zg-casino-game-card-top-row-gap',
  overlayPadding: '--zg-casino-game-card-overlay-padding',
  contentGap: '--zg-casino-game-card-content-gap',
  textGap: '--zg-casino-game-card-text-gap',
  iconButtonSize: '--zg-casino-game-card-icon-button-size',
  playButtonHeight: '--zg-casino-game-card-play-button-height',
  playButtonPaddingX: '--zg-casino-game-card-play-button-padding-x',
  playButtonGap: '--zg-casino-game-card-play-button-gap',
  disabledOpacity: '--zg-casino-game-card-disabled-opacity',
  transition: '--zg-casino-game-card-transition',
  focusRingColor: '--zg-casino-game-card-focus-ring-color',
  focusRingWidth: '--zg-casino-game-card-focus-ring-width',
  focusRingOffset: '--zg-casino-game-card-focus-ring-offset',
} as const;

export const gameCardTokens = casinoGameCardTokens;
