export const colorTokens = {
  primary: '--zg-color-primary',
  primaryHover: '--zg-color-primary-hover',
  primaryActive: '--zg-color-primary-active',
  primaryLight: '--zg-color-primary-light',
  primaryLighter: '--zg-color-primary-lighter',
  secondary: '--zg-color-secondary',
  secondaryHover: '--zg-color-secondary-hover',
  secondaryActive: '--zg-color-secondary-active',
  accent: '--zg-color-accent',
  highlight: '--zg-color-highlight',
  success: '--zg-color-success',
  successHover: '--zg-color-success-hover',
  successActive: '--zg-color-success-active',
  successLight: '--zg-color-success-light',
  warning: '--zg-color-warning',
  warningHover: '--zg-color-warning-hover',
  warningActive: '--zg-color-warning-active',
  warningLight: '--zg-color-warning-light',
  error: '--zg-color-error',
  errorHover: '--zg-color-error-hover',
  errorActive: '--zg-color-error-active',
  errorLight: '--zg-color-error-light',
  info: '--zg-color-info',
  infoHover: '--zg-color-info-hover',
  infoActive: '--zg-color-info-active',
  infoLight: '--zg-color-info-light',
  betBuilder: '--zg-color-bet-builder',
  live: '--zg-color-live',
  favorite: '--zg-color-favorite',
  betOpen: '--zg-color-bet-open',
  betWon: '--zg-color-bet-won',
  betLost: '--zg-color-bet-lost',
  betOther: '--zg-color-bet-other',
  surface: '--zg-color-surface',
  surfaceAlt: '--zg-color-surface-alt',
  surfaceHover: '--zg-color-surface-hover',
  border: '--zg-color-border',
  borderDark: '--zg-color-border-dark',
  textPrimary: '--zg-color-text-primary',
  textSecondary: '--zg-color-text-secondary',
  textDisabled: '--zg-color-text-disabled',
  textInverse: '--zg-color-text-inverse',
  textInfo: '--zg-color-text-info',
  bgPrimary: '--zg-color-bg-primary',
  bgSecondary: '--zg-color-bg-secondary',
  bgDark: '--zg-color-bg-dark',
  bgOverlay: '--zg-color-bg-overlay',
  bgCard: '--zg-color-bg-card',
  bgHeader: '--zg-color-bg-header',
} as const;

export const typographyTokens = {
  fontFamilyBase: '--zg-font-family-base',
  fontFamilySecondary: '--zg-font-family-secondary',
  fontSize: {
    xs: '--zg-font-size-xs',
    sm: '--zg-font-size-sm',
    base: '--zg-font-size-base',
    md: '--zg-font-size-md',
    lg: '--zg-font-size-lg',
    xl: '--zg-font-size-xl',
    '2xl': '--zg-font-size-2xl',
    '3xl': '--zg-font-size-3xl',
    '4xl': '--zg-font-size-4xl',
    '5xl': '--zg-font-size-5xl',
  },
  fontWeight: {
    light: '--zg-font-weight-light',
    regular: '--zg-font-weight-regular',
    medium: '--zg-font-weight-medium',
    semibold: '--zg-font-weight-semibold',
    bold: '--zg-font-weight-bold',
  },
  lineHeight: {
    tight: '--zg-line-height-tight',
    normal: '--zg-line-height-normal',
    relaxed: '--zg-line-height-relaxed',
  },
} as const;

export const typographyThemeTokens = {
  fontFamilyBase: '--zg-font-family-base',
  fontFamilySecondary: '--zg-font-family-secondary',
  fontSizeXs: '--zg-font-size-xs',
  fontSizeSm: '--zg-font-size-sm',
  fontSizeBase: '--zg-font-size-base',
  fontSizeMd: '--zg-font-size-md',
  fontSizeLg: '--zg-font-size-lg',
  fontSizeXl: '--zg-font-size-xl',
  fontSize2xl: '--zg-font-size-2xl',
  fontSize3xl: '--zg-font-size-3xl',
  fontSize4xl: '--zg-font-size-4xl',
  fontSize5xl: '--zg-font-size-5xl',
  fontWeightLight: '--zg-font-weight-light',
  fontWeightRegular: '--zg-font-weight-regular',
  fontWeightMedium: '--zg-font-weight-medium',
  fontWeightSemibold: '--zg-font-weight-semibold',
  fontWeightBold: '--zg-font-weight-bold',
  lineHeightTight: '--zg-line-height-tight',
  lineHeightNormal: '--zg-line-height-normal',
  lineHeightRelaxed: '--zg-line-height-relaxed',
} as const;

export const spacingTokens = {
  0: '--zg-spacing-0',
  1: '--zg-spacing-1',
  2: '--zg-spacing-2',
  3: '--zg-spacing-3',
  4: '--zg-spacing-4',
  5: '--zg-spacing-5',
  6: '--zg-spacing-6',
  8: '--zg-spacing-8',
  10: '--zg-spacing-10',
  12: '--zg-spacing-12',
  16: '--zg-spacing-16',
  20: '--zg-spacing-20',
  24: '--zg-spacing-24',
} as const;

export const radiusTokens = {
  none: '--zg-radius-none',
  sm: '--zg-radius-sm',
  base: '--zg-radius-base',
  md: '--zg-radius-md',
  lg: '--zg-radius-lg',
  xl: '--zg-radius-xl',
  '2xl': '--zg-radius-2xl',
  full: '--zg-radius-full',
} as const;

export const shadowTokens = {
  xs: '--zg-shadow-xs',
  sm: '--zg-shadow-sm',
  base: '--zg-shadow-base',
  md: '--zg-shadow-md',
  lg: '--zg-shadow-lg',
  xl: '--zg-shadow-xl',
} as const;

export const zIndexTokens = {
  dropdown: '--zg-z-index-dropdown',
  sticky: '--zg-z-index-sticky',
  fixed: '--zg-z-index-fixed',
  modalBackdrop: '--zg-z-index-modal-backdrop',
  modal: '--zg-z-index-modal',
  popover: '--zg-z-index-popover',
  tooltip: '--zg-z-index-tooltip',
} as const;

export const transitionTokens = {
  fast: '--zg-transition-fast',
  base: '--zg-transition-base',
  slow: '--zg-transition-slow',
} as const;
