export const luckyPickerTokens = {
  bg: '--zg-lucky-picker-bg',
  bgHighlight: '--zg-lucky-picker-bg-highlight',
  borderColor: '--zg-lucky-picker-border-color',
  borderColorHighlight: '--zg-lucky-picker-border-color-highlight',
  radius: '--zg-lucky-picker-radius',
  titleColor: '--zg-lucky-picker-title-color',
  titleFontFamily: '--zg-lucky-picker-title-font-family',
  titleFontSize: '--zg-lucky-picker-title-font-size',
  titleFontWeight: '--zg-lucky-picker-title-font-weight',
  descriptionColor: '--zg-lucky-picker-description-color',
  descriptionFontFamily: '--zg-lucky-picker-description-font-family',
  descriptionFontSize: '--zg-lucky-picker-description-font-size',
  descriptionFontWeight: '--zg-lucky-picker-description-font-weight',
  gap: '--zg-lucky-picker-gap',
  contentGap: '--zg-lucky-picker-content-gap',
  paddingY: '--zg-lucky-picker-padding-y',
  paddingX: '--zg-lucky-picker-padding-x',
  paddingYSm: '--zg-lucky-picker-padding-y-sm',
  paddingXSm: '--zg-lucky-picker-padding-x-sm',
  paddingYLg: '--zg-lucky-picker-padding-y-lg',
  paddingXLg: '--zg-lucky-picker-padding-x-lg',
  disabledOpacity: '--zg-lucky-picker-disabled-opacity',
} as const;
