export const sectionTitleTokens = {
  textColor: '--zg-section-title-text-color',
  textColorPrimary: '--zg-section-title-text-color-primary',
  textColorSuccess: '--zg-section-title-text-color-success',
  fontFamilyBase: '--zg-section-title-font-family-base',
  fontFamilySecondary: '--zg-section-title-font-family-secondary',
  fontWeight: '--zg-section-title-font-weight',
  lineHeight: '--zg-section-title-line-height',
  fontSizeSm: '--zg-section-title-font-size-sm',
  fontSizeMd: '--zg-section-title-font-size-md',
  fontSizeLg: '--zg-section-title-font-size-lg',
  gap: '--zg-section-title-gap',
  accentGap: '--zg-section-title-accent-gap',
  accentBaseWidth: '--zg-section-title-accent-base-width',
  accentSegmentWidth: '--zg-section-title-accent-segment-width',
  accentHeight: '--zg-section-title-accent-height',
  accentBaseColor: '--zg-section-title-accent-base-color',
  accentWarningColor: '--zg-section-title-accent-warning-color',
  accentSuccessColor: '--zg-section-title-accent-success-color',
} as const;
