import { type CasinoCatalogSnapshot } from './casino-demo.types';

export const ALL_GAMES_FIXTURE: CasinoCatalogSnapshot = {
  mode: 'all-games',
  title: 'All games',
  selectedCategory: 'all',
  heroImageUrl: null,
  parallaxImageUrl: null,
  snapshotAt: '2026-02-23T03:31:00Z',
  sourceUrls: ['https://www.sorti.ec/casino/all', 'https://www.sorti.ec/casino/all-games'],
  categories: [
    {
      id: 'all',
      label: 'All categories',
      gamesCount: null,
    },
    {
      id: 'slots',
      label: 'Slots',
      gamesCount: 18998,
    },
    {
      id: 'videoslots',
      label: 'Videoslots',
      gamesCount: 6202,
    },
    {
      id: 'live-dealer',
      label: 'Live dealer',
      gamesCount: 1186,
    },
    {
      id: 'othergames',
      label: 'Othergames',
      gamesCount: 540,
    },
    {
      id: 'blackjack',
      label: 'Blackjack',
      gamesCount: 490,
    },
    {
      id: 'roulette',
      label: 'Roulette',
      gamesCount: 309,
    },
    {
      id: 'instant-win',
      label: 'Instant win',
      gamesCount: 293,
    },
    {
      id: 'tablegames',
      label: 'Tablegames',
      gamesCount: 234,
    },
    {
      id: 'table-cards',
      label: 'Table & cards',
      gamesCount: 226,
    },
    {
      id: 'crash',
      label: 'Crash',
      gamesCount: 224,
    },
    {
      id: 'scratchcards',
      label: 'Scratchcards',
      gamesCount: 207,
    },
    {
      id: 'baccarat',
      label: 'Baccarat',
      gamesCount: 173,
    },
  ],
  games: [
    {
      id: '8453',
      title: 'White Buffalo Miracles',
      provider: 'Boldplay',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/white_buffalo_miracles.jpg',
    },
    {
      id: '8071',
      title: 'Oculltum 81',
      provider: 'Apollo Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/oculltum_81.jpg',
    },
    {
      id: '8853',
      title: 'Celestial Beauty',
      provider: 'Skywind',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/celestial_beauty.jpg',
    },
    {
      id: '11468',
      title: 'Treasure Bowl',
      provider: 'KA Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/treasure_bowl.jpg',
    },
    {
      id: '19707',
      title: 'Double Vault',
      provider: 'GMW',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/double_vault.jpg',
    },
    {
      id: '9094',
      title: 'Speed Auto Roulette',
      provider: 'Pragmatic Play Live',
      category: 'Roulette',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/speed_auto_roulette.jpg',
    },
    {
      id: '9808',
      title: 'Jinn Spring Oasis',
      provider: '7777 gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/jinn_spring_oasis.jpg',
    },
    {
      id: '4099',
      title: 'Joker Supreme',
      provider: 'Kalamba',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/joker_supreme.jpg',
    },
    {
      id: '9415',
      title: 'Budai Reels Bonus Buy',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/budai_reels_bonus_buy.jpg',
    },
    {
      id: '14430',
      title: 'Jelly Slice',
      provider: 'Hacksaw Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/jelly_slice.jpg',
    },
    {
      id: '1587',
      title: 'Total Overdrive',
      provider: 'BetSoft',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/total_overdrive.jpg',
    },
    {
      id: '5101',
      title: 'Golden Casino',
      provider: 'Espresso Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/golden_casino.jpg',
    },
    {
      id: '7677',
      title: 'RetroFest',
      provider: 'Retro Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/retrofest.jpg',
    },
    {
      id: '7964',
      title: "Santa's Gift",
      provider: 'Endorphina',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/santas_gift.jpg',
    },
    {
      id: '17175',
      title: 'Royal Gardens 10 lines',
      provider: 'Amusnet',
      category: 'Dice',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/royal_gardens_10_lines.jpg',
    },
    {
      id: '9492',
      title: 'Mine Field',
      provider: 'Evoplay',
      category: 'Mine',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/mine_field.jpg',
    },
    {
      id: '21814',
      title: 'Mahjong King',
      provider: 'Eurasian Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/mahjong_king.jpg',
    },
    {
      id: '3467',
      title: 'Punk Rocker',
      provider: 'Nolimit City',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/punk_rocker.jpg',
    },
    {
      id: '4177',
      title: 'Bounty Gold',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/bounty_gold.jpg',
    },
    {
      id: '19492',
      title: 'Piggy Mania',
      provider: 'Playtech',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/piggy_mania.jpg',
    },
    {
      id: '4771',
      title: 'Alice in Adventureland',
      provider: 'Fantasma Games',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/alice_in_adventureland.jpg',
    },
    {
      id: '6812',
      title: 'Arabian Secret',
      provider: 'Ruby Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/arabian_secret.jpg',
    },
    {
      id: '11812',
      title: 'Cricket Winner',
      provider: 'KA Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/cricket_winner.jpg',
    },
    {
      id: '18193',
      title: 'Striking Coin Link: Running Wins',
      provider: 'Fugaso',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/striking_coin_link_running_wins.jpg',
    },
    {
      id: '6842',
      title: 'Wild Shark Bonus Buy',
      provider: 'Amatic',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wild_shark_bonus_buy.jpg',
    },
    {
      id: '1127',
      title: 'Sizzling 777',
      provider: 'Wazdan',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/sizzling_777.jpg',
    },
    {
      id: '16775',
      title: 'Monkey Treasure',
      provider: 'Vibra Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/monkey_treasure.jpg',
    },
    {
      id: '19735',
      title: 'Stunning 7',
      provider: 'Skywind',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/stunning_7.jpg',
    },
    {
      id: '12066',
      title: 'Lights, Camera, Cash!',
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/lights_camera_cash.jpg',
    },
    {
      id: '8381',
      title: 'Fish! Shoot For Cash',
      provider: 'Playtech',
      category: 'Shooting',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/fish_shoot_for_cash.jpg',
    },
    {
      id: '6201',
      title: 'Bet On Poker Live',
      provider: 'Playtech',
      category: 'Poker',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/bet_on_poker_live.jpg',
    },
    {
      id: '17539',
      title: 'Twister',
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/twister.jpg',
    },
    {
      id: '20204',
      title: 'Classic Keno',
      provider: 'Parlay',
      category: 'Keno',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/classic_keno.jpg',
    },
    {
      id: '11033',
      title: 'Mighty Khan',
      provider: 'Skywind',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/mighty_khan.jpg',
    },
    {
      id: '16549',
      title: '100 Bracelets',
      provider: '7777 gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/100_bracelets.jpg',
    },
    {
      id: '20877',
      title: 'Treasure Legio',
      provider: 'Triple Cherry',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/treasure_legio.jpg',
    },
    {
      id: '13110',
      title: '100 Power Hot Dice',
      provider: 'Amusnet',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/100_power_hot_dice.jpg',
    },
    {
      id: '3434',
      title: 'The Tablet of Amun Ra',
      provider: 'Leander Games',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/the_tablet_of_amun_ra.jpg',
    },
    {
      id: '19218',
      title: 'Strength of Hercules',
      provider: 'Hacksaw Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/strength_of_hercules.jpg',
    },
    {
      id: '8085',
      title: 'Smiling Joker II',
      provider: 'Apollo Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/smiling_joker_ii.jpg',
    },
    {
      id: '14384',
      title: 'The Power of Kitsune',
      provider: 'PopOk',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/the_power_of_kitsune.jpg',
    },
    {
      id: '8398',
      title: 'Fabulous Fairies',
      provider: 'Boldplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/fabulous_fairies.jpg',
    },
    {
      id: '12329',
      title: 'River Queen',
      provider: 'Novomatic',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/river_queen.jpg',
    },
    {
      id: '1546',
      title: 'Monster Pop',
      provider: 'BetSoft',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/monster_pop.jpg',
    },
    {
      id: '21138',
      title: 'Royal Shooter',
      provider: 'TaDa Gaming',
      category: 'Instant Win',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/royal_shooter.jpg',
    },
    {
      id: '11315',
      title: 'Plinkgoal',
      provider: 'Gaming Corps',
      category: 'Plinko',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/plinkgoal.jpg',
    },
    {
      id: '4824',
      title: 'Bet on Teen Patti',
      provider: 'Ezugi',
      category: 'Poker',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/bet_on_teen_patti.jpg',
    },
    {
      id: '1040',
      title: 'Burning Stars',
      provider: 'Wazdan',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/burning_stars.jpg',
    },
    {
      id: '12967',
      title: 'Book of Wizard',
      provider: '3Oaks',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/book_of_wizard.jpg',
    },
    {
      id: '18563',
      title: 'Club Mr. Luck Christmas',
      provider: '7777 gaming',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/club_mr_luck_christmas.jpg',
    },
    {
      id: '249',
      title: 'Egyptian Fortunes',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/egyptian_fortunes.jpg',
    },
    {
      id: '11320',
      title: 'Destino Das Almas',
      provider: 'Gaming Corps',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/destino_das_almas.jpg',
    },
    {
      id: '1930',
      title: "Who's the Bride",
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/whos_the_bride.jpg',
    },
    {
      id: '4605',
      title: 'Colossal Cash Zone',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/colossal_cash_zone.jpg',
    },
    {
      id: '12851',
      title: 'Sun of Egypt 4',
      provider: 'Booongo',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/sun_of_egypt_4.jpg',
    },
    {
      id: '8459',
      title: 'Star Dragon',
      provider: 'Boldplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/star_dragon.jpg',
    },
    {
      id: '2226',
      title: 'Knights',
      provider: 'Red Rake Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/knights.jpg',
    },
    {
      id: '9392',
      title: 'Massive Luck',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/massive_luck.jpg',
    },
    {
      id: '9444',
      title: 'Gold of Sirens',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/gold_of_sirens.jpg',
    },
    {
      id: '8225',
      title: 'Blackjack 63 - Azure',
      provider: 'Pragmatic Play Live',
      category: 'Blackjack',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/blackjack_63__azure.jpg',
    },
    {
      id: '17497',
      title: "Robin Hood's Heroes",
      provider: 'Microgaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/robin_hoods_heroes.jpg',
    },
    {
      id: '15240',
      title: 'Graffiti in Sydney',
      provider: 'Onlyplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/graffiti_in_sydney.jpg',
    },
    {
      id: '8147',
      title: "Lil' Santa Bonus Buy",
      provider: 'Fugaso',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/lil_santa_bonus_buy.jpg',
    },
    {
      id: '18926',
      title: 'Sacred Owl',
      provider: 'GMW',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/sacred_owl.jpg',
    },
    {
      id: '9377',
      title: 'Inner Fire',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/inner_fire.jpg',
    },
    {
      id: '5387',
      title: 'Bingo Pirata',
      provider: 'Caleta',
      category: 'Bingo',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/bingo_pirata.jpg',
    },
    {
      id: '8471',
      title: 'Biker Santa: Bells Angels',
      provider: 'Boldplay',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/biker_santa_bells_angels.jpg',
    },
    {
      id: '3747',
      title: 'Wolf Fang',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wolf_fang.jpg',
    },
    {
      id: '8933',
      title: 'Fire Blaze: Toltec Blocks',
      provider: 'Playtech',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/fire_blaze_toltec_blocks.jpg',
    },
    {
      id: '3978',
      title: "Tales of Asgard: Loki's Fortune",
      provider: "Play'n GO",
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/tales_of_asgard_lokis_fortune.jpg',
    },
    {
      id: '716',
      title: 'Powerspin',
      provider: 'Relax Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/powerspin.jpg',
    },
    {
      id: '10765',
      title: 'Dogo Fortune',
      provider: 'Pascal Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/dogo_fortune.jpg',
    },
    {
      id: '3573',
      title: 'Striker Goes Wild',
      provider: 'Eyecon',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/striker_goes_wild.jpg',
    },
    {
      id: '253',
      title: 'Safari King',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/safari_king.jpg',
    },
    {
      id: '14072',
      title: 'Clover Islands',
      provider: 'Amusnet',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/clover_islands.jpg',
    },
    {
      id: '14122',
      title: 'Crazy Guava Lock 2 Spin',
      provider: 'KA Gaming',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/crazy_guava_lock_2_spin.jpg',
    },
    {
      id: '14052',
      title: 'Release the Bison',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/release_the_bison.jpg',
    },
    {
      id: '19153',
      title: 'Football Streak Brazil',
      provider: 'Leap',
      category: 'Virtual Game',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/football_streak_brazil.jpg',
    },
    {
      id: '2298',
      title: "Gordon Ramsay Hell's Kitchen",
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/gordon_ramsay_hells_kitchen.jpg',
    },
    {
      id: '7446',
      title: 'Gladiators',
      provider: 'Endorphina',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/gladiators.jpg',
    },
    {
      id: '4679',
      title: 'Remember Gulag',
      provider: 'Nolimit City',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/remember_gulag.jpg',
    },
    {
      id: '445',
      title: "Santa's Kiss",
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/santas_kiss.jpg',
    },
    {
      id: '15788',
      title: 'Frog Creek',
      provider: 'Belatra',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/frog_creek.jpg',
    },
    {
      id: '5402',
      title: 'Señorita Calavera',
      provider: 'Caleta',
      category: 'Bingo',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/seorita_calavera.jpg',
    },
    {
      id: '805',
      title: "Santa's Gift Rush",
      provider: 'PG SOFT',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/santas_gift_rush.jpg',
    },
    {
      id: '3618',
      title: 'Crystal Lotus',
      provider: 'Eyecon',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/crystal_lotus.jpg',
    },
    {
      id: '13940',
      title: 'Monkey King: Path of Treasure',
      provider: 'Mancala Games',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/monkey_king_path_of_treasure.jpg',
    },
    {
      id: '14385',
      title: 'Roulette',
      provider: 'PopOk',
      category: 'Roulette',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/roulette.jpg',
    },
    {
      id: '4323',
      title: 'Story of Hercules',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/story_of_hercules.jpg',
    },
    {
      id: '3276',
      title: 'ZZ Top Roadside Riches',
      provider: "Play'n GO",
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/zz_top_roadside_riches.jpg',
    },
    {
      id: '5814',
      title: 'Queen Of Fire - Frozen Flames',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/queen_of_fire__frozen_flames.jpg',
    },
    {
      id: '11861',
      title: 'Clean House',
      provider: 'KA Gaming',
      category: 'Instant Win',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/clean_house.jpg',
    },
    {
      id: '13771',
      title: 'Roulette PopOK Aurum',
      provider: 'CreedRoomz',
      category: 'Roulette',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/roulette_popok_aurum.jpg',
    },
    {
      id: '7955',
      title: 'Magic Spins Xmas',
      provider: 'Wazdan',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/magic_spins_xmas.jpg',
    },
    {
      id: '9176',
      title: 'Agent 7',
      provider: '7777 gaming',
      category: 'Match & Win',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/agent_7.jpg',
    },
    {
      id: '17794',
      title: 'Book of Ra Deluxe Bonus Buy',
      provider: 'Novomatic',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/book_of_ra_deluxe_bonus_buy.jpg',
    },
    {
      id: '21301',
      title: 'American Sevens',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/american_sevens.jpg',
    },
    {
      id: '453',
      title: 'Vegas Wins',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/vegas_wins.jpg',
    },
    {
      id: '3687',
      title: 'Power of Gods: Hades',
      provider: 'Wazdan',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/power_of_gods_hades.jpg',
    },
    {
      id: '230',
      title: 'Aladdin and the Sorcerer',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/aladdin_and_the_sorcerer.jpg',
    },
    {
      id: '14387',
      title: 'Diamond Fruits',
      provider: 'PopOk',
      category: 'Roulette',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/diamond_fruits.jpg',
    },
    {
      id: '12561',
      title: 'Mermaids Wild',
      provider: 'Spinoro',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/mermaids_wild.jpg',
    },
    {
      id: '18323',
      title: 'Crazy Poki Boo',
      provider: 'PopOk',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/crazy_poki_boo.jpg',
    },
    {
      id: '13106',
      title: 'Magical Leprechaun',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/magical_leprechaun.jpg',
    },
    {
      id: '20259',
      title: 'Cash Crab Football',
      provider: 'ElaGames',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/cash_crab_football.jpg',
    },
    {
      id: '5358',
      title: 'Viking Madness',
      provider: 'Caleta',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/viking_madness.jpg',
    },
    {
      id: '3768',
      title: 'African Rampage',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/african_rampage.jpg',
    },
    {
      id: '11353',
      title: 'Stocked Bar',
      provider: 'KA Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/stocked_bar.jpg',
    },
    {
      id: '4585',
      title: 'Lost Mystery Chests',
      provider: 'BetSoft',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/lost_mystery_chests.jpg',
    },
    {
      id: '9222',
      title: 'Cash 40',
      provider: '7777 gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/cash_40.jpg',
    },
    {
      id: '17468',
      title: 'Lucky Riches Hyperspins',
      provider: 'Microgaming',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/lucky_riches_hyperspins.jpg',
    },
    {
      id: '8151',
      title: 'Wild Coyote Megaways',
      provider: 'OneTouch',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wild_coyote_megaways.jpg',
    },
    {
      id: '4393',
      title: 'Dance with the Devil',
      provider: 'Skywind',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/dance_with_the_devil.jpg',
    },
    {
      id: '12531',
      title: 'Lucky Bugs Garden',
      provider: 'Spinoro',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/lucky_bugs_garden.jpg',
    },
    {
      id: '7753',
      title: 'Turkish Roulette',
      provider: 'Pragmatic Play Live',
      category: 'Roulette',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/turkish_roulette.jpg',
    },
    {
      id: '8492',
      title: "Kelly's Magic 7's",
      provider: 'Skywind',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/kellys_magic_7s.jpg',
    },
    {
      id: '7064',
      title: 'Fire Hot 20',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/fire_hot_20.jpg',
    },
    {
      id: '6276',
      title: 'Nederlandstalige Roulette Live',
      provider: 'Playtech',
      category: 'Roulette',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/nederlandstalige_roulette_live.jpg',
    },
    {
      id: '12259',
      title: 'Stampede Rush Speedy Santa',
      provider: 'Ruby Play',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/stampede_rush_speedy_santa.jpg',
    },
    {
      id: '16501',
      title: 'Yeti Quest',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/yeti_quest.jpg',
    },
    {
      id: '11848',
      title: 'PlinkoS',
      provider: 'KA Gaming',
      category: 'Plinko',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/plinkos.jpg',
    },
    {
      id: '5489',
      title: 'Miami Multiplier',
      provider: 'Hacksaw Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/miami_multiplier.jpg',
    },
    {
      id: '8166',
      title: 'Fortune Llama',
      provider: 'Fantasma Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/fortune_llama.jpg',
    },
    {
      id: '6389',
      title: 'Queen of Alexandria',
      provider: 'Microgaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/queen_of_alexandria.jpg',
    },
    {
      id: '16703',
      title: 'King Arthur',
      provider: 'TaDa Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/king_arthur.jpg',
    },
    {
      id: '11982',
      title: 'Virtual! Horse Racing',
      provider: 'Playtech',
      category: 'Virtual Game',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/virtual_horse_racing.jpg',
    },
    {
      id: '8958',
      title: 'Vegas Repeat Wins',
      provider: 'Ruby Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/vegas_repeat_wins.jpg',
    },
    {
      id: '7213',
      title: 'Crack the Bank Hold and Win',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/crack_the_bank_hold_and_win.jpg',
    },
    {
      id: '9414',
      title: "St. Patrick's Magic Field",
      provider: 'Evoplay',
      category: 'Mine',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/st_patricks_magic_field.jpg',
    },
    {
      id: '6277',
      title: 'x1000 Quantum Roulette Live',
      provider: 'Playtech',
      category: 'Roulette',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/x1000_quantum_roulette_live.jpg',
    },
    {
      id: '2271',
      title: 'Holiday Spirits',
      provider: "Play'n GO",
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/holiday_spirits.jpg',
    },
    {
      id: '9397',
      title: 'Wolf Hiding',
      provider: 'Evoplay',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wolf_hiding.jpg',
    },
    {
      id: '19748',
      title: 'Wild Bandida',
      provider: 'Spinomenal',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wild_bandida.jpg',
    },
    {
      id: '10019',
      title: 'Heroes’ Realm',
      provider: 'Rival',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/heroes_realm.jpg',
    },
  ],
};
