import { type CasinoCatalogSnapshot } from './casino-demo.types';

export const MOST_BET_FIXTURE: CasinoCatalogSnapshot = {
  mode: 'most-bet',
  title: 'Most bet games',
  selectedCategory: 'all',
  heroImageUrl: null,
  parallaxImageUrl: null,
  snapshotAt: '2026-02-23T03:31:00Z',
  sourceUrls: ['https://www.sorti.ec/casino/most-bet'],
  categories: [
    {
      id: 'all',
      label: 'All categories',
      gamesCount: null,
    },
    {
      id: 'slots',
      label: 'Slots',
      gamesCount: 18998,
    },
    {
      id: 'videoslots',
      label: 'Videoslots',
      gamesCount: 6202,
    },
    {
      id: 'live-dealer',
      label: 'Live dealer',
      gamesCount: 1186,
    },
    {
      id: 'othergames',
      label: 'Othergames',
      gamesCount: 540,
    },
    {
      id: 'blackjack',
      label: 'Blackjack',
      gamesCount: 490,
    },
    {
      id: 'roulette',
      label: 'Roulette',
      gamesCount: 309,
    },
    {
      id: 'instant-win',
      label: 'Instant win',
      gamesCount: 293,
    },
    {
      id: 'tablegames',
      label: 'Tablegames',
      gamesCount: 234,
    },
    {
      id: 'table-cards',
      label: 'Table & cards',
      gamesCount: 226,
    },
    {
      id: 'crash',
      label: 'Crash',
      gamesCount: 224,
    },
    {
      id: 'scratchcards',
      label: 'Scratchcards',
      gamesCount: 207,
    },
    {
      id: 'baccarat',
      label: 'Baccarat',
      gamesCount: 173,
    },
  ],
  games: [
    {
      id: '6277',
      title: 'x1000 Quantum Roulette Live',
      provider: 'Playtech',
      category: 'Roulette',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/x1000_quantum_roulette_live.jpg',
    },
    {
      id: '6180',
      title: 'Book of Charms',
      provider: 'Realistic Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/book_of_charms.jpg',
    },
    {
      id: '4_pots_riches',
      title: '4 Pots Riches: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/4_pots_riches_hold_and_win.jpg',
    },
    {
      id: '67a22baf2b5971443f2b31ea',
      title: 'Bonza Bucks Hold and Win Extreme 10,000',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/bonza_bucks_hold_and_win_extreme_10000.jpg',
    },
    {
      id: 'coin_strike_2',
      title: 'Coin Strike 2: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/coin_strike_2_hold_and_win.jpg',
    },
    {
      id: 'thunder_coins_xxl',
      title: 'Thunder Coins XXL: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/thunder_coins_xxl_hold_and_win.jpg',
    },
    {
      id: 'MegaRoulette',
      title: 'Mega Roulette',
      provider: 'KAGaming',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mega_roulette.jpg',
    },
    {
      id: 'HiLo',
      title: 'HiLo',
      provider: 'KAGaming',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/hilo.jpg',
    },
    {
      id: 'charge_clovers',
      title: 'Charge the Clovers: Hit The Bonus™',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/charge_the_clovers_hit_the_bonus.jpg',
    },
    {
      id: 'S-FH01',
      title: 'Fiery Sevens Hot 5',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens_hot_5.jpg',
    },
    {
      id: 'scharged_clovers',
      title: 'Supercharged Clovers: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/supercharged_clovers_hold_and_win.jpg',
    },
    {
      id: '6013',
      title: 'Penalty Shoot-оut:Street',
      provider: 'Evoplay',
      category: 'OTHERGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/penalty_shootutstreet.jpg',
    },
    {
      id: 'S-FS02',
      title: 'Fiery Sevens Exclusive',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens_exclusive.jpg',
    },
    {
      id: 'S-FS01',
      title: 'Fiery Sevens',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens.jpg',
    },
    {
      id: 'aviator',
      title: 'Aviator',
      provider: 'Spribe',
      category: 'CRASHGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aviator.jpg',
    },
    {
      id: 'imperial_fruits_5',
      title: 'Imperial Fruits: 5 lines',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/imperial_fruits_5_lines.jpg',
    },
    {
      id: '65896',
      title: 'Sizzling 777 Deluxe',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sizzling_777_deluxe.jpg',
    },
    {
      id: 'joker_expand',
      title: 'Joker Expand: 5 Lines',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/joker_expand_5_lines.jpg',
    },
    {
      id: '580dc69068712a00a9000018',
      title: 'Classico',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/classico.jpg',
    },
    {
      id: 'JacksOrBetterVideoPoker',
      title: 'Jacks or Better',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/jacks_or_better.jpg',
    },
    {
      id: 'DoubleDoubleBonusPokerVideoPoker',
      title: 'Double Double Bonus Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/double_double_bonus_poker.jpg',
    },
    {
      id: 'BonusPokerVideoPoker',
      title: 'Bonus Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bonus_poker.jpg',
    },
    {
      id: 'AcesAndFacesVideoPoker',
      title: 'Aces and Faces',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aces_and_faces.jpg',
    },
    {
      id: '140000460',
      title: 'Blackjack 8',
      provider: 'Lucky Streak',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_8.jpg',
    },
    {
      id: '239000008',
      title: 'Chicken Road',
      provider: 'InOut Games',
      category: 'Instant Win',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/chicken_road.jpg',
    },
    {
      id: '158000022',
      title: '5 Lions Gold™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/5_lions_gold.jpg',
    },
    {
      id: '158000070',
      title: 'Hot to Burn™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/hot_to_burn.jpg',
    },
    {
      id: '158000108',
      title: 'Super 7s™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/super_7s.jpg',
    },
    {
      id: '140000023',
      title: 'Blackjack 16',
      provider: 'Lucky Streak',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_16.jpg',
    },
    {
      id: '478',
      title: 'Aztec Palace',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/aztec_palace.jpg',
    },
    {
      id: '451',
      title: 'Valley of Pharaohs',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/valley_of_pharaohs.jpg',
    },
    {
      id: '2295',
      title: 'Rome: The Golden Age',
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/rome_the_golden_age.jpg',
    },
    {
      id: '6341',
      title: 'Premier League Cricket',
      provider: 'Caleta',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/premier_league_cricket.jpg',
    },
    {
      id: '4_supercharged_clovers',
      title: '4 Supercharged Clovers: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/4_supercharged_clovers_hold_and_win.jpg',
    },
    {
      id: 'CashbahCafeVideoSlot',
      title: 'Ca$hbah Cafe',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/cahbah_cafe.jpg',
    },
    {
      id: '473',
      title: 'Hot Slot™: 777 Diamond Crown',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/hot_slot_777_diamond_crown.jpg',
    },
    {
      id: 'BoostRoulette',
      title: 'Boost Roulette',
      provider: 'KAGaming',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/boost_roulette.jpg',
    },
    {
      id: 'super_pink_joker',
      title: 'Super Pink Joker: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/super_pink_joker_hold_and_win.jpg',
    },
    {
      id: 'HappyBirthdayMrPresidentVideoSlot',
      title: 'Happy Birthday Mr President',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/happy_birthday_mr_president.jpg',
    },
    {
      id: 'lion_gems_3pots',
      title: 'Lion Gems 3 Pots: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/lion_gems_3_pots_hold_and_win.jpg',
    },
    {
      id: 'king_of_the_sky',
      title: 'King of the Sky: Hit the Bonus',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/king_of_the_sky_hit_the_bonus.jpg',
    },
    {
      id: 'cg_blackjackbeto',
      title: 'Blackjack Beto',
      provider: 'Caleta',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_beto.jpg',
    },
    {
      id: 'royal_express',
      title: 'Royal Express: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/royal_express_hold_and_win.jpg',
    },
    {
      id: '660d1e866b579800019456d7',
      title: 'The Wild Wings of Phoenix Deluxe',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/the_wild_wings_of_phoenix_deluxe.jpg',
    },
    {
      id: 'merry_giftmas',
      title: 'Merry Giftmas: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/merry_giftmas_hold_and_win.jpg',
    },
    {
      id: 'diamonds_power',
      title: 'Diamonds Power: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/diamonds_power_hold_and_win.jpg',
    },
    {
      id: '628215226698440014bd3bd9',
      title: 'The Wild Wings of Phoenix',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/the_wild_wings_of_phoenix.jpg',
    },
    {
      id: '604b38b89e1ee60016fdf21e',
      title: 'Wild Wild Vegas',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/wild_wild_vegas.jpg',
    },
    {
      id: '5643',
      title: 'Penalty Shoot Out',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/penalty_shoot_out.jpg',
    },
    {
      id: '158001118',
      title: 'Mines+',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mines.jpg',
    },
    {
      id: '158001115',
      title: 'Super Tiki Strike',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/super_tiki_strike.jpg',
    },
    {
      id: '158000990',
      title: 'Mummy’s Jewels',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mummys_jewels.jpg',
    },
    {
      id: '183000161',
      title: 'Aviatrix',
      provider: 'aviatrix',
      category: 'Crash',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aviatrix.jpg',
    },
    {
      id: '83100101',
      title: 'European Roulette',
      provider: 'Vibra Gaming',
      category: 'Video Poker',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/european_roulette.jpg',
    },
    {
      id: '134000038',
      title: 'Football Penalty Duel',
      provider: 'Leap',
      category: 'Virtual Sports',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/football_penalty_duel.jpg',
    },
    {
      id: '158000025',
      title: '7 Piggies™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/7_piggies.jpg',
    },
    {
      id: '140000024',
      title: 'Blackjack 7',
      provider: 'Lucky Streak',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_7.jpg',
    },
    {
      id: '6260',
      title: 'Colombia Blackjack Live',
      provider: 'Playtech',
      category: 'Blackjack',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/colombia_blackjack_live.jpg',
    },
    {
      id: '5687',
      title: 'Space Wars 2: Powerpoints',
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/space_wars_2_powerpoints.jpg',
    },
    {
      id: '6191',
      title: 'Adventures Beyond Wonderland Live',
      provider: 'Playtech',
      category: 'Wheel',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/adventures_beyond_wonderland_live.jpg',
    },
    {
      id: '6332',
      title: 'Monster Truck Madness',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/monster_truck_madness.jpg',
    },
    {
      id: 'ThornsAndTreasuresVideoSlot',
      title: 'Thorns And Treasures',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/thorns_and_treasures.jpg',
    },
    {
      id: 'DozenRoulette',
      title: 'Dozen Roulette',
      provider: 'KAGaming',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/dozen_roulette.jpg',
    },
    {
      id: 'BattleOfLuck',
      title: 'Battle Of Luck',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/battle_of_luck.jpg',
    },
    {
      id: 'KickCashMonkey2',
      title: 'Kick Cash Monkey2',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/kick_cash_monkey2.jpg',
    },
    {
      id: 'BlazinFireballsSpinNWinVideoSlot',
      title: "Blazin' Fireballs Spin 'n' Win",
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/blazin_fireballs_spin_n_win.jpg',
    },
    {
      id: '6338',
      title: 'American Sevens',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/american_sevens.jpg',
    },
    {
      id: 'ShamrockGoldVideoSlot',
      title: 'Shamrock Gold',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/shamrock_gold.jpg',
    },
    {
      id: '3_chillies_and_joker',
      title: '3 Chillies and Joker: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_chillies_and_joker_hold_and_win.jpg',
    },
    {
      id: '3_luxor_pots',
      title: '3 Luxor Pots: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_luxor_pots_hold_and_win.jpg',
    },
    {
      id: 'cg_blackjackroyale',
      title: 'Blackjack Royale',
      provider: 'Caleta',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_royale.jpg',
    },
    {
      id: 'FrogsBall',
      title: "Frog's Ball Lock 2 Spin",
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/frogs_ball_lock_2_spin.jpg',
    },
    {
      id: 'thunder_coins',
      title: 'Thunder Coins: Hold & Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/thunder_coins_hold__win.jpg',
    },
    {
      id: '3_magic_lamps',
      title: '3 Magic Lamps: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_magic_lamps_hold_and_win.jpg',
    },
    {
      id: '3pots_extra',
      title: '3 Pots Riches Extra: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_pots_riches_extra_hold_and_win.jpg',
    },
    {
      id: '432',
      title: 'Mighty Symbols™: Crowns',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mighty_symbols_crowns.jpg',
    },
    {
      id: 'coin_strike',
      title: 'Coin Strike: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/coin_strike_hold_and_win.jpg',
    },
    {
      id: 'PiggyBankMachine',
      title: 'Piggy Bank Machine',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/piggy_bank_machine.jpg',
    },
    {
      id: 'mines',
      title: 'Mines',
      provider: 'TurboGames',
      category: 'OTHERGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mines.jpg',
    },
    {
      id: 'luxor_gold',
      title: 'Luxor Gold: Hold And Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/luxor_gold_hold_and_win.jpg',
    },
    {
      id: '5e732986ba03bd00171b05bb',
      title: 'Burning Classics',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/burning_classics.jpg',
    },
    {
      id: 'TripleDoubleBonusPokerVideoPoker',
      title: 'Triple Double Bonus Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/triple_double_bonus_poker.jpg',
    },
    {
      id: 'JokerPokerVideoPoker',
      title: 'Joker Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/joker_poker.jpg',
    },
    {
      id: 'BonusPokerDeluxeVideoPoker',
      title: 'Bonus Poker Deluxe',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bonus_poker_deluxe.jpg',
    },
    {
      id: '80500149',
      title: 'Carnival Treasure',
      provider: 'SA Gaming',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/carnival_treasure.jpg',
    },
    {
      id: '6230',
      title: 'Soirée Privée Blackjack Live',
      provider: 'Playtech',
      category: 'Blackjack',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/soire_prive_blackjack_live.jpg',
    },
    {
      id: 'SummerFireworksFestival',
      title: 'Summer Fireworks Festival',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/summer_fireworks_festival.jpg',
    },
    {
      id: 'SGMummyHunter',
      title: 'Mummy Hunter',
      provider: 'Habanero',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mummy_hunter.jpg',
    },
    {
      id: 'MegaWildWest',
      title: 'Mega Wild West',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mega_wild_west.jpg',
    },
    {
      id: '67a22bda2b5971443f2b31ed',
      title: 'Liberty and Freedom Hold and Win Extreme 10,000',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/liberty_and_freedom_hold_and_win_extreme_10000.jpg',
    },
    {
      id: '3xcatch',
      title: '3x Catch',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/3x_catch.jpg',
    },
    {
      id: 'S-FH02',
      title: 'Fiery Sevens Hot 20',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens_hot_20.jpg',
    },
    {
      id: 'jingle_coins',
      title: 'Jingle Coins: Hold And Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/jingle_coins_hold_and_win.jpg',
    },
    {
      id: 'light_clovers',
      title: 'Lightning Clovers: Hit the Bonus™',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/lightning_clovers_hit_the_bonus.jpg',
    },
    {
      id: 'S-AL02',
      title: 'Alchemy Quest Level Up',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/alchemy_quest_level_up.jpg',
    },
    {
      id: '3carts_of_gold',
      title: '3 Carts of Gold: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_carts_of_gold_hold_and_win.jpg',
    },
    {
      id: '446',
      title: 'Mighty Wild™: Panther Grand Gold Edition',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/mighty_wild_panther_grand_gold_edition.jpg',
    },
    {
      id: 'sherwood_coins',
      title: 'Sherwood Coins: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/sherwood_coins_hold_and_win.jpg',
    },
    {
      id: '6038',
      title: 'Thunder Mega Sevens Bonus Buy',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/thunder_mega_sevens_bonus_buy.jpg',
    },
    {
      id: '777sizzling_wins',
      title: '777 Sizzling Wins: 5 Lines',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/777_sizzling_wins_5_lines.jpg',
    },
    {
      id: '425',
      title: '12 Coins™',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/12_coins.jpg',
    },
    {
      id: '376',
      title: 'Sic Bo Dragons',
      provider: 'Wazdan',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sic_bo_dragons.jpg',
    },
    {
      id: 'MobileSPAtlanticCityBlackjack',
      title: 'Atlantic City Blackjack Touch',
      provider: 'Genii',
      category: 'TABLEGAMES',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/atlantic_city_blackjack_touch.jpg',
    },
    {
      id: '83100669',
      title: 'Balkanian Rhapsody 2',
      provider: 'Spinthon',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/balkanian_rhapsody_2.jpg',
    },
    {
      id: '158001011',
      title: 'Alien Invaders',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/alien_invaders.jpg',
    },
    {
      id: '80500144',
      title: 'Ultra Roulette',
      provider: 'SA Gaming',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/ultra_roulette.jpg',
    },
    {
      id: '80700103',
      title: '3 Carts of Gold: Hold and Win',
      provider: 'Playson',
      category: 'Slots',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_carts_of_gold_hold_and_win.jpg',
    },
    {
      id: '83100152',
      title: 'Blackjack',
      provider: 'Vibra Gaming',
      category: 'Video Poker',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack.jpg',
    },
    {
      id: '158000332',
      title: 'Sugar Rush',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sugar_rush.jpg',
    },
    {
      id: '158000029',
      title: 'Ancient Egypt Classic™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/ancient_egypt_classic.jpg',
    },
    {
      id: '158000047',
      title: 'Egyptian Fortunes™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/egyptian_fortunes.jpg',
    },
    {
      id: '140000008',
      title: 'Roulette 1',
      provider: 'Lucky Streak',
      category: 'Live Dealer',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/roulette_1.jpg',
    },
  ],
};
