import { type CasinoCatalogSnapshot } from './casino-demo.types';

export const MOST_PLAYED_FIXTURE: CasinoCatalogSnapshot = {
  mode: 'most-played-games',
  title: 'Most played games',
  selectedCategory: 'all',
  heroImageUrl: null,
  parallaxImageUrl: null,
  snapshotAt: '2026-02-23T03:31:00Z',
  sourceUrls: ['https://www.sorti.ec/casino/most-played-games'],
  categories: [
    {
      id: 'all',
      label: 'All categories',
      gamesCount: null,
    },
    {
      id: 'slots',
      label: 'Slots',
      gamesCount: 18998,
    },
    {
      id: 'videoslots',
      label: 'Videoslots',
      gamesCount: 6202,
    },
    {
      id: 'live-dealer',
      label: 'Live dealer',
      gamesCount: 1186,
    },
    {
      id: 'othergames',
      label: 'Othergames',
      gamesCount: 540,
    },
    {
      id: 'blackjack',
      label: 'Blackjack',
      gamesCount: 490,
    },
    {
      id: 'roulette',
      label: 'Roulette',
      gamesCount: 309,
    },
    {
      id: 'instant-win',
      label: 'Instant win',
      gamesCount: 293,
    },
    {
      id: 'tablegames',
      label: 'Tablegames',
      gamesCount: 234,
    },
    {
      id: 'table-cards',
      label: 'Table & cards',
      gamesCount: 226,
    },
    {
      id: 'crash',
      label: 'Crash',
      gamesCount: 224,
    },
    {
      id: 'scratchcards',
      label: 'Scratchcards',
      gamesCount: 207,
    },
    {
      id: 'baccarat',
      label: 'Baccarat',
      gamesCount: 173,
    },
  ],
  games: [
    {
      id: '2295',
      title: 'Rome: The Golden Age',
      provider: 'NetEnt',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/rome_the_golden_age.jpg',
    },
    {
      id: '4_supercharged_clovers',
      title: '4 Supercharged Clovers: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/4_supercharged_clovers_hold_and_win.jpg',
    },
    {
      id: '4_pots_riches',
      title: '4 Pots Riches: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/4_pots_riches_hold_and_win.jpg',
    },
    {
      id: '67a22baf2b5971443f2b31ea',
      title: 'Bonza Bucks Hold and Win Extreme 10,000',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/bonza_bucks_hold_and_win_extreme_10000.jpg',
    },
    {
      id: '473',
      title: 'Hot Slot™: 777 Diamond Crown',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/hot_slot_777_diamond_crown.jpg',
    },
    {
      id: 'coin_strike_2',
      title: 'Coin Strike 2: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/coin_strike_2_hold_and_win.jpg',
    },
    {
      id: 'thunder_coins_xxl',
      title: 'Thunder Coins XXL: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/thunder_coins_xxl_hold_and_win.jpg',
    },
    {
      id: 'king_of_the_sky',
      title: 'King of the Sky: Hit the Bonus',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/king_of_the_sky_hit_the_bonus.jpg',
    },
    {
      id: 'ShamrockGoldVideoSlot',
      title: 'Shamrock Gold',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/shamrock_gold.jpg',
    },
    {
      id: 'charge_clovers',
      title: 'Charge the Clovers: Hit The Bonus™',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/charge_the_clovers_hit_the_bonus.jpg',
    },
    {
      id: 'S-FH01',
      title: 'Fiery Sevens Hot 5',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens_hot_5.jpg',
    },
    {
      id: 'merry_giftmas',
      title: 'Merry Giftmas: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/merry_giftmas_hold_and_win.jpg',
    },
    {
      id: '432',
      title: 'Mighty Symbols™: Crowns',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mighty_symbols_crowns.jpg',
    },
    {
      id: 'S-FS02',
      title: 'Fiery Sevens Exclusive',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens_exclusive.jpg',
    },
    {
      id: 'S-FS01',
      title: 'Fiery Sevens',
      provider: 'SpadeGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/fiery_sevens.jpg',
    },
    {
      id: 'imperial_fruits_5',
      title: 'Imperial Fruits: 5 lines',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/imperial_fruits_5_lines.jpg',
    },
    {
      id: '65896',
      title: 'Sizzling 777 Deluxe',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sizzling_777_deluxe.jpg',
    },
    {
      id: 'joker_expand',
      title: 'Joker Expand: 5 Lines',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/joker_expand_5_lines.jpg',
    },
    {
      id: 'JacksOrBetterVideoPoker',
      title: 'Jacks or Better',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/jacks_or_better.jpg',
    },
    {
      id: 'DoubleDoubleBonusPokerVideoPoker',
      title: 'Double Double Bonus Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/double_double_bonus_poker.jpg',
    },
    {
      id: 'BonusPokerVideoPoker',
      title: 'Bonus Poker',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bonus_poker.jpg',
    },
    {
      id: 'AcesAndFacesVideoPoker',
      title: 'Aces and Faces',
      provider: 'Genii',
      category: 'VIDEOPOKER',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aces_and_faces.jpg',
    },
    {
      id: '158001115',
      title: 'Super Tiki Strike',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/super_tiki_strike.jpg',
    },
    {
      id: '239000008',
      title: 'Chicken Road',
      provider: 'InOut Games',
      category: 'Instant Win',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/chicken_road.jpg',
    },
    {
      id: '158000022',
      title: '5 Lions Gold™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/5_lions_gold.jpg',
    },
    {
      id: '158000025',
      title: '7 Piggies™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/7_piggies.jpg',
    },
    {
      id: '158000029',
      title: 'Ancient Egypt Classic™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/ancient_egypt_classic.jpg',
    },
    {
      id: '158000070',
      title: 'Hot to Burn™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/hot_to_burn.jpg',
    },
    {
      id: '158000108',
      title: 'Super 7s™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/super_7s.jpg',
    },
    {
      id: '5907',
      title: 'Neptune Bingo',
      provider: 'Eurasian Gaming',
      category: 'Bingo',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/neptune_bingo.jpg',
    },
    {
      id: '478',
      title: 'Aztec Palace',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/aztec_palace.jpg',
    },
    {
      id: '451',
      title: 'Valley of Pharaohs',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/valley_of_pharaohs.jpg',
    },
    {
      id: '442',
      title: 'Paris Nights',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/paris_nights.jpg',
    },
    {
      id: '5897',
      title: 'Fortune Festival',
      provider: 'Eurasian Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/fortune_festival.jpg',
    },
    {
      id: '6341',
      title: 'Premier League Cricket',
      provider: 'Caleta',
      category: 'Slots',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/premier_league_cricket.jpg',
    },
    {
      id: 'LuckyMoney',
      title: 'Lucky Money',
      provider: 'KAGaming',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/lucky_money.jpg',
    },
    {
      id: '2028',
      title: '9 Thunderbolts',
      provider: 'Gamzix',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/9_thunderbolts.jpg',
    },
    {
      id: '3_royal_coins',
      title: '3 Royal Coins: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_royal_coins_hold_and_win.jpg',
    },
    {
      id: 'rockin_joker',
      title: 'Rockin’ Joker: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/rockin_joker_hold_and_win.jpg',
    },
    {
      id: 'lion_gems_3pots',
      title: 'Lion Gems 3 Pots: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/lion_gems_3_pots_hold_and_win.jpg',
    },
    {
      id: '660d1e866b579800019456d7',
      title: 'The Wild Wings of Phoenix Deluxe',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/the_wild_wings_of_phoenix_deluxe.jpg',
    },
    {
      id: 'light_clovers',
      title: 'Lightning Clovers: Hit the Bonus™',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/lightning_clovers_hit_the_bonus.jpg',
    },
    {
      id: 'scharged_clovers',
      title: 'Supercharged Clovers: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/supercharged_clovers_hold_and_win.jpg',
    },
    {
      id: '65978',
      title: '15 Coins™ Grand Gold Edition Score the Jackpot',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/15_coins_grand_gold_edition_score_the_jackpot.jpg',
    },
    {
      id: '1638832',
      title: 'Mighty Symbols™: Crowns Easter Edition',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/mighty_symbols_crowns_easter_edition.jpg',
    },
    {
      id: 'diamonds_power',
      title: 'Diamonds Power: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/diamonds_power_hold_and_win.jpg',
    },
    {
      id: '6038',
      title: 'Thunder Mega Sevens Bonus Buy',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/thunder_mega_sevens_bonus_buy.jpg',
    },
    {
      id: '6013',
      title: 'Penalty Shoot-оut:Street',
      provider: 'Evoplay',
      category: 'OTHERGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/penalty_shootutstreet.jpg',
    },
    {
      id: 'coin_strike',
      title: 'Coin Strike: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/coin_strike_hold_and_win.jpg',
    },
    {
      id: '425',
      title: '12 Coins™',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/12_coins.jpg',
    },
    {
      id: 'aviator',
      title: 'Aviator',
      provider: 'Spribe',
      category: 'CRASHGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aviator.jpg',
    },
    {
      id: '580dc69068712a00a9000018',
      title: 'Classico',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/classico.jpg',
    },
    {
      id: '83100669',
      title: 'Balkanian Rhapsody 2',
      provider: 'Spinthon',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/balkanian_rhapsody_2.jpg',
    },
    {
      id: '158001118',
      title: 'Mines+',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mines.jpg',
    },
    {
      id: '158000990',
      title: 'Mummy’s Jewels',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mummys_jewels.jpg',
    },
    {
      id: '158000781',
      title: 'Big Bass Halloween 2',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/big_bass_halloween_2.jpg',
    },
    {
      id: '183000161',
      title: 'Aviatrix',
      provider: 'aviatrix',
      category: 'Crash',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/aviatrix.jpg',
    },
    {
      id: '83100037',
      title: 'Amazing Yu',
      provider: 'Felix',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/amazing_yu.jpg',
    },
    {
      id: '6277',
      title: 'x1000 Quantum Roulette Live',
      provider: 'Playtech',
      category: 'Roulette',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/x1000_quantum_roulette_live.jpg',
    },
    {
      id: '459',
      title: 'Wunderfest',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/wunderfest.jpg',
    },
    {
      id: '220',
      title: 'Mysterious',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/mysterious.jpg',
    },
    {
      id: '6180',
      title: 'Book of Charms',
      provider: 'Realistic Games',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/book_of_charms.jpg',
    },
    {
      id: 'vegas_glitz',
      title: 'Vegas Glitz',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/vegas_glitz.jpg',
    },
    {
      id: '68543e7f263be371f3c65909',
      title: 'Diamonds Diamonds Diamonds Hold and Win',
      provider: 'BoomingGames',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/diamonds_diamonds_diamonds_hold_and_win.jpg',
    },
    {
      id: 'tornado_power',
      title: 'Tornado Power: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/tornado_power_hold_and_win.jpg',
    },
    {
      id: 'diamonds_power_xxl',
      title: 'Diamonds Power XXL: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/diamonds_power_xxl_hold_and_win.jpg',
    },
    {
      id: 'flaming_bells',
      title: 'Flaming Bells: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/flaming_bells_hold_and_win.jpg',
    },
    {
      id: 'crown_strike',
      title: 'Crown Strike: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/crown_strike_hold_and_win.jpg',
    },
    {
      id: '474',
      title: 'Bells of Fortune',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bells_of_fortune.jpg',
    },
    {
      id: 'royal_express',
      title: 'Royal Express: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/royal_express_hold_and_win.jpg',
    },
    {
      id: '3_luxor_pots',
      title: '3 Luxor Pots: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_luxor_pots_hold_and_win.jpg',
    },
    {
      id: '3pots_extra',
      title: '3 Pots Riches Extra: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_pots_riches_extra_hold_and_win.jpg',
    },
    {
      id: 'luxor_gold',
      title: 'Luxor Gold: Hold And Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/luxor_gold_hold_and_win.jpg',
    },
    {
      id: 'burning_wins',
      title: 'Burning Wins',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/burning_wins.jpg',
    },
    {
      id: '158001120',
      title: '3 Magic Eggs',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/3_magic_eggs.jpg',
    },
    {
      id: '158001113',
      title: 'Floating Dragon Wild Horses',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/floating_dragon_wild_horses.jpg',
    },
    {
      id: '158000948',
      title: 'Big Bass Bonanza 1000',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/big_bass_bonanza_1000.jpg',
    },
    {
      id: '158000859',
      title: 'Lucky’s Wild Pub',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/luckys_wild_pub.jpg',
    },
    {
      id: '158000658',
      title: 'Sweet Bonanza 1000',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sweet_bonanza_1000.jpg',
    },
    {
      id: '158000623',
      title: 'Big Bass Secrets of the Golden Lake',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/big_bass_secrets_of_the_golden_lake.jpg',
    },
    {
      id: '158000412',
      title: 'Hot Pepper',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/hot_pepper.jpg',
    },
    {
      id: '83100101',
      title: 'European Roulette',
      provider: 'Vibra Gaming',
      category: 'Video Poker',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/european_roulette.jpg',
    },
    {
      id: '83100099',
      title: 'Goleada Millonaria',
      provider: 'Vibra Gaming',
      category: 'Scratch Card',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/goleada_millonaria.jpg',
    },
    {
      id: '158000024',
      title: '7 Monkeys™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/7_monkeys.jpg',
    },
    {
      id: '158000047',
      title: 'Egyptian Fortunes™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/egyptian_fortunes.jpg',
    },
    {
      id: '158000088',
      title: 'Master Joker™',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/master_joker.jpg',
    },
    {
      id: '470',
      title: 'Super Boom',
      provider: 'Booming',
      category: 'Slots',
      sourceImageUrl: 'https://casino-api.zgameslatam.com/images/aleaplay/super_boom.jpg',
    },
    {
      id: '6260',
      title: 'Colombia Blackjack Live',
      provider: 'Playtech',
      category: 'Blackjack',
      sourceImageUrl:
        'https://casino-api.zgameslatam.com/images/aleaplay/colombia_blackjack_live.jpg',
    },
    {
      id: '6438',
      title: 'Love and Luck Joker',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/love_and_luck_joker.jpg',
    },
    {
      id: 'golden_penny_2',
      title: 'x1000 Golden Penny 2',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/x1000_golden_penny_2.jpg',
    },
    {
      id: 'DozenRoulette',
      title: 'Dozen Roulette',
      provider: 'KAGaming',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/dozen_roulette.jpg',
    },
    {
      id: '536929569',
      title: '16 Coins Platinum Burning Board',
      provider: 'Wazdan',
      category: 'OTHERGAMES',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/16_coins_platinum_burning_board.jpg',
    },
    {
      id: 'cg_bingobingo',
      title: 'Bingo Bingo',
      provider: 'Caleta',
      category: 'BINGO',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bingo_bingo.jpg',
    },
    {
      id: '6338',
      title: 'American Sevens',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/american_sevens.jpg',
    },
    {
      id: 'cg_blackjackbeto',
      title: 'Blackjack Beto',
      provider: 'Caleta',
      category: 'TABLEGAMES',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/blackjack_beto.jpg',
    },
    {
      id: 'GoldNSpinVideoSlot',
      title: 'Gold ‘N’ Spin',
      provider: 'Genii',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/gold_n_spin.jpg',
    },
    {
      id: '3carts_of_gold',
      title: '3 Carts of Gold: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/3_carts_of_gold_hold_and_win.jpg',
    },
    {
      id: 'thunder_coins',
      title: 'Thunder Coins: Hold & Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/thunder_coins_hold__win.jpg',
    },
    {
      id: '446',
      title: 'Mighty Wild™: Panther Grand Gold Edition',
      provider: 'Wazdan',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/mighty_wild_panther_grand_gold_edition.jpg',
    },
    {
      id: '6086',
      title: 'Ultra Coin Magnetic Bonus Buy',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/ultra_coin_magnetic_bonus_buy.jpg',
    },
    {
      id: 'cg_megabingo',
      title: 'Mega Bingo',
      provider: 'Caleta',
      category: 'BINGO',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/mega_bingo.jpg',
    },
    {
      id: 'buffalo_power_2',
      title: 'Buffalo Power 2: Hold and Win',
      provider: 'Playson',
      category: 'VIDEOSLOTS',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/buffalo_power_2_hold_and_win.jpg',
    },
    {
      id: '5921',
      title: 'Inner Fire',
      provider: 'Evoplay',
      category: 'VIDEOSLOTS',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/inner_fire.jpg',
    },
    {
      id: '193000148',
      title: 'Secrets of Papyrus',
      provider: 'Mascot Gaming',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/secrets_of_papyrus.jpg',
    },
    {
      id: '158001114',
      title: 'Dragon Tiger Fortunes',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/dragon_tiger_fortunes.jpg',
    },
    {
      id: '84600028',
      title: 'Irish Coins Hold & Win',
      provider: 'Revolver',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/irish_coins_hold__win.jpg',
    },
    {
      id: '158000980',
      title: 'Majestic Express – Gold Run',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/majestic_express__gold_run.jpg',
    },
    {
      id: '158000961',
      title: 'Gates of Olympus Super Scatter',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl:
        'https://api-casino.zgames.tech/images/aleaplay/gates_of_olympus_super_scatter.jpg',
    },
    {
      id: '158000838',
      title: 'Bigger Bass Splash',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/bigger_bass_splash.jpg',
    },
    {
      id: '158000665',
      title: 'Hot to Burn Multiplier',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/hot_to_burn_multiplier.jpg',
    },
    {
      id: '158000332',
      title: 'Sugar Rush',
      provider: 'Pragmatic Play',
      category: 'Slots',
      sourceImageUrl: 'https://api-casino.zgames.tech/images/aleaplay/sugar_rush.jpg',
    },
  ],
};
